<!doctype html>
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>GM - About Us</title>
    <link rel="stylesheet" type="text/css" href="../views/css/style.css" />
</head>

<body>

<%@include file="common/header2.jspf"%>

<div class="container" >
    <main>
        <h2 class="heading" align="center">About Us</h2>
        <div class="about" style="display: flex">
            <img src="../views/img/about.png" width="400" align="center" alt="about" draggable="false" usemap="#image-map">
            <!-- Image Map Generated by http://www.image-map.net/ -->
            <map name="image-map">
                <area target="" alt="ater" title="ater" href="shop" coords="293,452,91" shape="circle">
                <area target="" alt="misr" title="misr" href="shop" coords="476,378,81" shape="circle">
                <area target="" alt="bakela" title="bakela" href="shop" coords="114,341,91" shape="circle">
                <area target="" alt="boleke" title="boleke" href="home" coords="225,136,113" shape="circle">
                <area target="" alt="shimbra" title="shimbra" href="shop" coords="409,207,82" shape="circle">
                <area target="_blank" alt="kitel" title="kitel" href="home" coords="236,325,279,340,318,344,364,344,380,313,348,278,314,256,263,252,212,265" shape="poly">
            </map>
            <p style=" font-size: 20px; line-height: 2">
                We strive to offer excellent services to our prestigious customers & are known for trusted & superior quality of products. All the products are stored safely in our clean & updated store. Understanding our customer’s need & demand, we provide a wide variety of pulses & cereals of high nutritional value. With the professional approach to a traditional niche, we offer prompt & on-time services.
            </p>
        </div>
    </main> <!-- Main Area -->
</div>

<%@include file="common/footer.jspf"%>
</body>
</html>